# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Run Automated Tests"

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64,arm"
  test:
    runs-on: ubuntu-latest
    needs: qemu
    timeout-minutes: 30
    # strategy:
    #   matrix:
    #     node-version: [18]
    # node-version: [14.x, 16.x, 18.x]
    # arch: [armv7]
    # arch: [armv7, aarch64]
    container:
      image: "arm32v7/node:18-bullseye"
      # options: --user 1000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies and run tests
        run: |
          mkdir -p $HOME/magicmirror
          cp -r . $HOME/magicmirror/
          cd $HOME/magicmirror
          # Xvfb :99 -screen 0 1024x768x16 &
          # export DISPLAY=:99
          id
          pwd
          ls -la
          npm run install-mm:dev
          touch css/custom.css
          npm run test:prettier
          npm run test:js
          npm run test:css
          # npm run test
          npm run test:unit
          npm run test:e2e
